language: perl
perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

before_install:
  - cpanm -n Module::Build
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  perl Build.PL && ./Build build && cover -test +ignore Build.pm -report coveralls
