--- #YAML:1.0
name: AudioFile-Info
version: 1.04
license: perl
distribution_type: module
requires:
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  AudioFile::Info:
    file: lib/AudioFile/Info.pm
    version: 1.04
generated_by: Module::Build version 0.20
