--- #YAML:1.0
name: AudioFile-Info
version: 1.07
author:
  - Dave Cross, E<lt>dave@dave.org.ukE<gt>
abstract: Perl extension to get info from audio files.
license: perl
requires:
  YAML: 0
  perl: 5.6.0
provides:
  AudioFile::Info:
    file: lib/AudioFile/Info.pm
    version: 1.07
generated_by: Module::Build version 0.2607
